name: Actions CI
  
on:
  pull_request:
    branches: [main]
   
permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: write
   
jobs:
  test:
    name: Run Build, Test and Publish Reports
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
            distribution: 'corretto'
            java-version: '21'
   
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
   
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
   
      - name: Run Build with Gradle
        run: ./gradlew build --build-cache
        
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: build/test-results/**/*.xml
   
      - name: Generate Kover Coverage Report
        run: ./gradlew koverXmlReport
   
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1.3.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: build/reports/kover/report.xml
